### ISSUE TITLE
无法正常更新订阅

### ISSUE THREAD

**Issue by sherlockHlb** [Quan666/ELF_RSS#425] opened 2023-04-23 04:02 UTC
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

2.6.17
nonebot2+gocqhttp

### 列出安装的 Python 包

nb plugin安装

### 如何复现

无法更新订阅

### 实际行为

04-23 11:56:47 [ERROR] logging | Job "check_update (trigger: interval[0:05:00], next run at: 2023-04-23 12:01:50 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\ELF_RSS2\my_trigger.py", line 23, in check_update
    await asyncio.wait_for(rss_parsing.start(rss), timeout=wait_for)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\ELF_RSS2\rss_parsing.py", line 82, in start
    new_rss, cached = await fetch_rss(rss)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\ELF_RSS2\rss_parsing.py", line 163, in fetch_rss
    if not config.rsshub_backup and not config.debug:
AttributeError: 'ELFConfig' object has no attribute 'debug'

**Comment by NekoAria** [comment] 2023-04-23 08:06
Duplicate of #413 #419

**Closed as completed by NekoAria** 2023-04-23 08:06 UTC
Labels: bug
